// Targeted by JavaCPP version 1.5.11: DO NOT EDIT THIS FILE

package us.ihmc.abilityhand;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static us.ihmc.abilityhand.global.abilityhand.*;


@NoOffset @Properties(inherit = us.ihmc.abilityhand.AbilityHandJavaAPIConfig.class)
public class AHWrapper extends Pointer {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public AHWrapper(Pointer p) { super(p); }

  public AHWrapper(@Cast("const uint8_t") byte hand_addr, @Cast("const uint32_t") int b_rate) { super((Pointer)null); allocate(hand_addr, b_rate); }
  private native void allocate(@Cast("const uint8_t") byte hand_addr, @Cast("const uint32_t") int b_rate);
  public native int connect();
  public native int read_write_once(@Const @ByRef FloatArray6 cmd_values,
                        @Cast("const Command") int cmd, @Cast("const uint8_t") byte reply_mode);
  public native @MemberGetter @Const @ByRef Hand hand();
  public native @Cast("size_t") long n_reads(); public native AHWrapper n_reads(long setter);
  public native @Cast("size_t") long n_writes(); public native AHWrapper n_writes(long setter);
}
