// Targeted by JavaCPP version 1.5.11: DO NOT EDIT THIS FILE

package us.ihmc.abilityhand;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static us.ihmc.abilityhand.global.abilityhand.*;

@Name("std::array<float,6>") @Properties(inherit = us.ihmc.abilityhand.AbilityHandJavaAPIConfig.class)
public class FloatArray6 extends Pointer {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public FloatArray6(Pointer p) { super(p); }
    public FloatArray6()       { allocate();  }
    private native void allocate();
    public native @Name("operator =") @ByRef FloatArray6 put(@ByRef FloatArray6 x);

    public boolean empty() { return size() == 0; }
    public native long size();

    public float front() { return get(0); }
    public float back() { return get(size() - 1); }
    @Index public native float get(@Cast("size_t") long i);
    public native FloatArray6 put(@Cast("size_t") long i, float value);
}

