// Targeted by JavaCPP version 1.5.11: DO NOT EDIT THIS FILE

package us.ihmc.abilityhand;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static us.ihmc.abilityhand.global.abilityhand.*;


@NoOffset @Properties(inherit = us.ihmc.abilityhand.AbilityHandJavaAPIConfig.class)
public class Hand extends Pointer {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public Hand(Pointer p) { super(p); }

  public Hand(@Cast("const uint8_t") byte h_address) { super((Pointer)null); allocate(h_address); }
  private native void allocate(@Cast("const uint8_t") byte h_address);
  public native @ByRef FloatArray6 pos(); public native Hand pos(FloatArray6 setter);
  public native @ByRef FloatArray6 vel(); public native Hand vel(FloatArray6 setter);
  public native @ByRef FloatArray6 cur(); public native Hand cur(FloatArray6 setter);
  public native @ByRef UInt16Array30 fsr(); public native Hand fsr(UInt16Array30 setter);
  @MemberGetter public native @Cast("const uint8_t") @Name("address") byte _address();
}
