// Targeted by JavaCPP version 1.5.11: DO NOT EDIT THIS FILE

package us.ihmc.abilityhand;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static us.ihmc.abilityhand.global.abilityhand.*;

@Name("std::array<uint16_t,30>") @Properties(inherit = us.ihmc.abilityhand.AbilityHandJavaAPIConfig.class)
public class UInt16Array30 extends Pointer {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public UInt16Array30(Pointer p) { super(p); }
    public UInt16Array30()       { allocate();  }
    private native void allocate();
    public native @Name("operator =") @ByRef UInt16Array30 put(@ByRef UInt16Array30 x);

    public boolean empty() { return size() == 0; }
    public native long size();

    public short front() { return get(0); }
    public short back() { return get(size() - 1); }
    @Index public native @Cast("uint16_t") short get(@Cast("size_t") long i);
    public native UInt16Array30 put(@Cast("size_t") long i, short value);
}

