// Targeted by JavaCPP version 1.5.11: DO NOT EDIT THIS FILE

package us.ihmc.abilityhand.global;

import us.ihmc.abilityhand.*;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

public class abilityhand extends us.ihmc.abilityhand.AbilityHandJavaAPIConfig {
    static { Loader.load(); }

// Targeting ../FloatArray6.java


// Targeting ../UInt16Array30.java


// Parsed from wrapper.h

// #pragma once

// #include <chrono>

// #include "hand.h"
// #include "ppp.h"
// #include "linux_serial.h"

@MemberGetter public static native @Cast("const uint16_t") short BUFFER_SIZE();
@MemberGetter public static native @Cast("const uint16_t") short STUFFED_BUFFER_SIZE();

/** enum Command */
public static final int POSITION = 0, VELOCITY = 1, CURRENT = 2, DUTY = 3;
// Targeting ../AHWrapper.java




// Parsed from hand.h

// #pragma once
// #include <array>
// #include <cstdint>
// Targeting ../Hand.java



}
